name: Build Multi-Arch Binaries

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Auto get all dependencies
        run: |
          # 自动获取所有依赖
          go mod download
          # 自动整理go.mod文件
          go mod tidy

      - name: Build ARM64 static binary
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o bin/webdav-simulator-arm64 ./main.go

      - name: Build AMD64 static binary
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/webdav-simulator-amd64 ./main.go

      - name: Verify binaries
        run: |
          file bin/webdav-simulator-arm64
          file bin/webdav-simulator-amd64
          ! ldd bin/webdav-simulator-amd64 2>&1 | grep -q "not a dynamic executable" || echo "Static binary verified"

      - name: Commit binaries
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add bin/
          git commit -m "Add static binaries [auto-deps]"
          git push