name: Build Static Multi-Arch Binaries

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: |
          go mod tidy
          go get golang.org/x/net/webdav

      - name: Build Static ARM64 Binary
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o bin/webdav-simulator-arm64 ./main.go

      - name: Build Static AMD64 Binary
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/webdav-simulator-amd64 ./main.go

      - name: Verify Binaries
        run: |
          file bin/webdav-simulator-arm64
          file bin/webdav-simulator-amd64
          # 检查是否为静态链接
          ldd bin/webdav-simulator-amd64 2>&1 | grep -q "not a dynamic executable" || exit 1
          echo "Static binaries verified"

      - name: Get timestamp
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Commit binaries
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add bin/
          git commit -m "Add static binaries (arm64+amd64) built at ${{ steps.date.outputs.date }}"
          git push