name: Build Static Multi-Arch Binaries

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: |
          go mod tidy
          go get golang.org/x/net/webdav

      - name: Build ARM64 binary (static)
        run: |
          mkdir -p bin
          docker run --rm --platform linux/arm64 \
            -v "$PWD":/usr/src/myapp \
            -w /usr/src/myapp \
            golang:1.21-alpine \
            sh -c 'CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o bin/webdav-simulator-arm64 ./main.go'

      - name: Build AMD64 binary (static)
        run: |
          mkdir -p bin
          docker run --rm --platform linux/amd64 \
            -v "$PWD":/usr/src/myapp \
            -w /usr/src/myapp \
            golang:1.21-alpine \
            sh -c 'CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/webdav-simulator-amd64 ./main.go'

      - name: Verify binaries
        run: |
          file bin/webdav-simulator-arm64
          file bin/webdav-simulator-amd64
          ! ldd bin/webdav-simulator-amd64 2>&1 | grep -q "not a dynamic executable" || echo "Static binary verified"

      - name: Commit binaries
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add bin/
          git commit -m "Add static multi-arch binaries"
          git push