name: Build Multi-Arch Binaries

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # 匹配 go.mod 要求
          check-latest: true  # 确保获取最新补丁版本

      - name: Verify Go version
        run: |
          go version
          echo "GOROOT=$(go env GOROOT)"

      - name: Get dependencies
        run: |
          go mod tidy
          go get golang.org/x/net/webdav

      - name: Build ARM64 static binary
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o bin/webdav-simulator-arm64 ./main.go

      - name: Build AMD64 static binary
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/webdav-simulator-amd64 ./main.go

      - name: Verify binaries
        run: |
          file bin/webdav-simulator-arm64
          file bin/webdav-simulator-amd64
          ! ldd bin/webdav-simulator-amd64 2>&1 | grep -q "not a dynamic executable" || echo "Static binary verified"

      - name: Commit binaries
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add bin/
          git commit -m "Add static binaries built with Go 1.23"
          git push